version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/base:current
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello earth" # run the `echo` command
      - run: printenv
