version: 2.1
jobs:
  build:
    docker: 
      - image: alpine:latest # the primary container, where your job's commands are run
    resource_class: server/server
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello earth" # run the `echo` command
